language: node_js
node_js:
  - 6.0.0
  - 5.0.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "vY7hE1HkobRZenEkwxfbV0AUU0l6p1KflYSnCaJlTCogiCER4cnacGsGyzMp0X1rkmno7U+vViTM8VwqeUgXFD2810qlWfDEQace+EiWjS2Jj4YjpUxFtXcR1nsqXxRqDrzeLCZnFV7shAg8VYP+p3cOlqjsKCvFR58xjOvQTsqoNO+xlJVdDdOQb81bPwnYtsJfT+m96qsZ5xDKML5pvp6JVzvoVorQtuT2CNqx9kG424s5+152+4mCpXQK82VvJAKhtrgsDzN/c+iu7hj/we6b/zhocEj531DNwoh/6GJr/g5FwjU4qbq/R3WGUnrxoDsrcS8e7c50UFGwGdQhbPFSlfheiyXG74fCIXSO42OzgTqqcQzzqDfBXtq5taBoRXLVmWVYBcc7tRtvLhTXcK8cPRC5WRxae9JejDFCNsDOASRxo/wo3pwQMdTZsYgn/c3X42ASeNQ3mfzrzPzHnG32uVxgsKgi5FqUeCi9QFtWGt3/wg38eOBlMwZsM8xnT6LRrNZ4S0sxHSbQpao82E3R9VvxGUhdLI6AlrQ1B6NZffBZEurm+zKYlzuBWq1GRAE2xly58EsQB+MmXSSvq/jOaaPl3/UUVh4ItMPbuaf0Rt3SgBTNPHA7bz6PtwqQfqkEVBcCI7xxiwvenT2hq8VZV6sL71WnkuNcvMVh3VA="
